name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Update to your desired AWS region

    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${008971675564.dkr.ecr.us-east-1.amazonaws.com/accuknox}

    - name: Build Docker Image
      run: |
        docker build -t ${008971675564.dkr.ecr.us-east-1.amazonaws.com/accuknox}/wisecow-app:latest .

    - name: Push Docker Image to ECR
      run: |
        docker push ${008971675564.dkr.ecr.us-east-1.amazonaws.com/accuknox}/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/wisecow-deployment.yaml
        kubectl apply -f k8s/wisecow-service.yaml

